### ISSUE TITLE
Promoted not working

### ISSUE THREAD

**Issue by willwade** [ACECentre/aacnews#16]
Not sure the promoted flag is doing anything. Should raise it to top of that section and put a label of "promoted" after author

e.g. something like:

![screen shot 2016-11-23 at 10 33 02](https://cloud.githubusercontent.com/assets/229352/20558522/48027d40-b168-11e6-8fbb-9188aae62ddb.png)

**Comment by lemol** [comment]
Just have to update the template file [mailchimp-assets/AACinfo.html](https://github.com/ACECentre/aacnews/commit/16850507cfaf210eea8b4bcca840d1a2143b780f#diff-8d85475fef53ef8ff12f4e66a527ae9d) to maichimp.
