### ISSUE TITLE
cant bring up edit screen

### ISSUE THREAD

**Issue by willwade** [ACECentre/aacnews#32]
Not sure why - see video here https://www.dropbox.com/s/r0wy8pq340jvgxx/AACInfoBug.mov?dl=0

**Comment by willwade** [comment]
Still not fixed...

![screen shot 2018-01-05 at 14 54 58](https://user-images.githubusercontent.com/229352/34614417-5117452a-f229-11e7-8f19-4b2fad380971.png)
![screen shot 2018-01-05 at 14 55 24](https://user-images.githubusercontent.com/229352/34614419-51329244-f229-11e7-95c6-83200473393c.png)

**Comment by willwade** [comment]
NB: This is fixed by restarting the app. Odd

**Comment by hosseinamin** [comment]
Fixed
